#!/bin/sh

# The config for repo-init

# shellcheck disable=SC2034

#*******[ Configurations ]*******#

TOOLS_DIR=./tools

TOOLS_LIST="
commitlint-install
commitlint-git-hooks
cforge-install
"

COMMITLINT_USE_GLOBAL_EXECUTABLE=1
